reviews:
  exclude:
    - "**/*.txt"
    - "**/*.md"
    - ".taskmaster/**"
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/*.log"
    - "**/.env*"
    - "**/coverage/**"
  include:
    - "mabar-frontend/src/**"
    - "cloud/**"
    - "src/**"
    - "scripts/**"
    - "*.js"
    - "*.ts"
    - "*.vue"
    - "*.json"
    - "*.yaml"
    - "*.yml"