reviews:
  path_filters:
    - "mabar-frontend/src/**"
    - "cloud/**"
    - "src/**"
    - "*.js"
    - "*.ts"
    - "*.vue"
    - "*.json"
    - "*.yaml"
    - "*.yml"
    - "!**/*.txt"
    - "!**/*.md"
    - "!.taskmaster/**"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/*.log"
    - "!**/.env*"
    - "!**/coverage/**"
    - "!scripts/**"